#pragma config(Sensor, in1,    lf1,            sensorLineFollower)
#pragma config(Sensor, dgtl1,  rled,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  gled,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  bswitch1,       sensorTouch)
#pragma config(Sensor, dgtl4,  bswitch2,       sensorTouch)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_cm)
#pragma config(Motor,  port1,           rwmotor,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           lwmotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           beltmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftmotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forw ();
void backw();
void liftbelt ();
void lowerbelt();
void turnbelt ();
int turn = 0;




task main()
{
	while (1==1) {
		forw();
		liftbelt ();
		turnbelt ();
		lowerbelt ();
		backw();
	}
}



void forw () {
while (SensorValue(lf1) < 500) {
	startMotor(lwmotor, 100);
	startMotor(rwmotor, 100);
	}
	stopMotor(lwmotor);
	stopMotor(lwmotor);
}

void backw () {
	while (SensorValue(sonar) < 500) {
		startMotor(lwmotor, -100);
	startMotor(rwmotor, -100);
	}
	stopMotor(lwmotor);
	stopMotor(lwmotor);
}

void liftbelt () {
	clearTimer(T1);
	while (time1[T1] < 5000) {
		startMotor(liftmotor, 50);
	}
	stopMotor(liftmotor);
}

void turnbelt () {
	clearTimer(T1);
	while (time1[T1] < 5000) {
		if (turn % 2 == 0){
		startMotor(beltmotor, -100);
		}
		else if (turn % 2 == 1){
		startMotor(beltmotor, 100);
	}
	stopMotor(beltmotor);
	}
	turn++;
}

void lowerbelt () {
	clearTimer(T1);
	while (time1[T1] < 5000) {
		startMotor(liftmotor, -50);
		}
	stopMotor(liftmotor);
	}
